### ISSUE TITLE
Add support for ps3 and psvita online status and game presence 

### ISSUE THREAD

**Issue by MixaMega** [achievements-app/psn-api#104]

**Comment by wescopeland** [comment]
Closed due to lack of information/clarity.

**Comment by MixaMega** [comment]
> Could you please provide more information about what you are looking for in regards to support for PS3 and PS Vita online status and game presence? Are you looking for a specific function that is missing from the library, or would this require the creation of a new function?

When I'm online on my PS3 it still shows that im offline in something like  ProfileFromUserNameResponse.profile.presences
But im not sure if this could be implemented since it also shows that im offline in the PS App, the only place where it does appear as online is another PS3 or Vita

> Additionally, it would be helpful if you could provide a reference to another library that offers this functionality so that we can potentially port it to psn-api.

There aren't any that im aware of
