### ISSUE TITLE
Unable to get PSN access code

### ISSUE THREAD

**Issue by Jorrex** [achievements-app/psn-api#105]
Hi,

I'm running into an issue where my freshly generated NPSSO code cannot be used to generate the PSN access code.
This worked before, but is currently not doing anything anymore.

Even if I renew my SSO code or use a different account to generate it, I'm still given the same error:
_There was a problem retrieving your PSN access code. Is your NPSSO code valid?_

I don't think this is an issue with this package, but any idea what could be causing this?

**Comment by wescopeland** [comment]
It appears Sony may have changed something again:
https://github.com/Tustin/psn-php/issues/232

I'm at work right now but I'll be following this throughout the day. If it surfaces that there are any changes we need to make to get this working again I'll ensure they're made ASAP.

**Comment by wescopeland** [comment]
https://github.com/achievements-app/psn-api/pull/106

**Comment by wescopeland** [comment]
@Jorrex @spypix3l @Asteroidxx @FunkeyFlo This should be resolved in https://github.com/achievements-app/psn-api/releases/tag/v2.8.2. Thanks for your patience. Let me know if any issues arise after updating.
