### ISSUE TITLE
exchangeRefreshTokenForAuthTokens not work

### ISSUE THREAD

**Issue by shirohako** [achievements-app/psn-api#107]
exchangeRefreshTokenForAuthTokens() does not work for me.

I see that in version 2.8.2, auth scopes string have changed, please update file `exchangeRefreshTokenForAuthTokens.ts`. thanks

**Comment by wescopeland** [comment]
Hi, thanks for reporting this. This should be fixed in 2.8.3.

https://github.com/achievements-app/psn-api/releases/tag/v2.8.3
