### ISSUE TITLE
ACCESS DENIED - GIVE NEW API

### ISSUE THREAD

**Issue by ArabCrew786** [achievements-app/psn-api#143]
Access Denied
You don't have permission to access "http://ca.account.sony.com/api/authz/v3/oauth" on this server.

Guys if there is new api pls update it

I try send a POST request
with POST DATA
**access_type=offline&client_id=09515159-7237-4370-9b40-3806e67c0891&redirect_uri=com.scee.psxandroid.scecompcall://redirect&response_type=code&scope=psn:mobile.v2.core psn:clientapp**

Keep getting Access Denied

**Comment by ArabCrew786** [comment]
Again same thing 
https://ca.account.sony.com/api/authz/v3/oauth
Response code: 403 (Forbidden)

### Is a there an updated like maybe a v4/oauth

**Comment by wescopeland** [comment]
>Guys if there is new api pls update it

Friendly reminder: psn-api is provided for free to you and is built on hundreds of hours of collective work, also done for free. There's a way to ask for support, and making demands in all caps text isn't it.
