### ISSUE TITLE
cant get it to work with react js

### ISSUE THREAD

**Issue by LS2355** [achievements-app/psn-api#149]
I can't seem to fetch any data when using react but if i just use plain vanilla JS it work great.

This one works great (vanilla JS)
![idk](https://github.com/achievements-app/psn-api/assets/108366585/3e1debc8-434c-42a1-8bad-e071bf5c75cf)

but whenever i try to do the same thing in react i keep getting an 403 / forbidden error or an incorrect Npsso error. (the npsso is 100% correct)

![Screenshot 2023-09-19 195220](https://github.com/achievements-app/psn-api/assets/108366585/78fa5358-a973-43fa-a3cd-dfaf0a4c4ece)
![idk-react](https://github.com/achievements-app/psn-api/assets/108366585/aea8d1e8-668a-4a6d-b901-d9ebb73b0fb6)

if possible can you get back to me with a possible solution. Pretty sure i'm just messing up somewhere but i cant seem to find it

thing to note: 
I added a proxy to the package.json file it was :localhost://8080. just in case that is useful

**Comment by LS2355** [comment]
Client side

**Comment by wescopeland** [comment]
Sony themselves block client-side calls with their CORS policy. To get this working, you'll probably need to set up an API layer in Node.js that uses psn-api, then have your React front-end call those API endpoints.
