### ISSUE TITLE
Having problems with Cors using the api in Ionic framework

### ISSUE THREAD

**Issue by FernandoFiorini** [achievements-app/psn-api#150]
Access to fetch at '**psnURL**' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Have to install any plugins?

**Comment by wescopeland** [comment]
Sony themselves are responsible for this CORS policy, which Ionic is going to honor. For calling the endpoints client-side, you'll need to set up a Node.js API which uses psn-api that your Ionic app calls, rather than using psn-api directly within your Ionic app.
