### ISSUE TITLE
HeaderOverride for lang

### ISSUE THREAD

**Issue by c-peiron** [achievements-app/psn-api#157]
I have seen in the documentation that it is possible to overwrite the header to send the language ISO, how can I do it?

**Comment by wescopeland** [comment]
@c-peiron For the sake of someone who stumbles upon this issue, did you manage to resolve this?

**Comment by c-peiron** [comment]
Sorry, I completely forgot to leave the solution here. For those who want to get the descriptions and titles of the translated trophies, you must also send the following:

```
const { trophies: titleTrophies } = await getTitleTrophies(
    authorization,
    gameId,
    "all",
    {
      npServiceName: trophyTitlePlatform !== "PS5" ? "trophy" : undefined,
      headerOverrides: {"Accept-Language":  'Es-es'}
    }
  );
```
