### ISSUE TITLE
Add more examples to docs site

### ISSUE THREAD

**Issue by wescopeland** [achievements-app/psn-api#16]

**Comment by TheYuriG** [comment]
What documentation examples are we currently missing? I've noticed the [friends list](https://github.com/achievements-app/psn-api/issues/34#issuecomment-997057877) one so far.

**Comment by wescopeland** [comment]
Generally there isn't anything absent, but more examples are always good!

**Comment by TheYuriG** [comment]
I'll look into it halfway through March and see what I can add then.
