### ISSUE TITLE
Add docs for using psn-api via CDN such as skypack

### ISSUE THREAD

**Issue by wescopeland** [achievements-app/psn-api#24]

**Comment by wescopeland** [comment]
Related https://github.com/skypackjs/skypack-cdn/issues/235

**Comment by TheYuriG** [comment]
Just FYI, the [entry](https://www.skypack.dev/view/psn-api) is outdated, still listing PSNAWP as PHP wrapper and missing at least some contributors at the bottom.

**Comment by wescopeland** [comment]
I've decided to close this as I'm not sure we should even be recommending to use this library in client-side settings anymore.
