### ISSUE TITLE
Error in retrieving npsso

### ISSUE THREAD

**Issue by mleonelli** [achievements-app/psn-api#48]
Hi,
on the same browser (Edge) where I am logged in to my PSN profile and navigating the URL in README.md I am receiving

{"error":"invalid_grant","error_description":"Invalid login","error_code":20,"docs":"https://auth.api.sonyentertainmentnetwork.com/docs/","parameters":[]}

I am looking at a reason for this error

**Comment by wescopeland** [comment]
Hi,

This error occurs when you are not authenticated to PSN. Perhaps your auth cookie isn't being stored properly by Edge. I recommend trying a different browser and seeing if you get the same error.

**Comment by mleonelli** [comment]
Thanks @wescopeland, indeed it seems a browser issue. Worked OK on Google Chrome Version 97.0.4692.99 (Official Build) (64-bit) and failed on Microsoft Edge Version 97.0.1072.62 (Official build) (64-bit).

Anything to document anywere? Worth it? Otherwise I am happy to close the issue!

**Comment by wescopeland** [comment]
Hey @mleonelli Thank you for the update & confirmation!

I will update the documentation later tonight to reference this issue and known problems with getting an NPSSO using MS Edge.

**Comment by wescopeland** [comment]
Additional note about using another browser added via https://github.com/achievements-app/psn-api/commit/cb385305715fa7238d09c13fe2fbbcad6c6234af.
