### ISSUE TITLE
trophy languages Only English and Japanese

### ISSUE THREAD

**Issue by jacklee0122** [achievements-app/psn-api#70]
My English is pretty basic.
Using the options: headerOverrides: {"Accept-Language": "zh-tw"} for getUserTitles() and getTitleTrophies() only got trophies with English and Japanese but no traditional Chinese for trophy name and description.

Using "ja-jp" works.

LEGO NINJAGO MOVIE: THE VIDEOGAME for example.
https://psnprofiles.com/trophies/6675-lego-ninjago-movie-the-videogame?lang=zh-tw

**Comment by Azimiao** [comment]
Hello, pls use those params:

 `zh-Hant` for  Traditional Chinese (繁体中文/HK/TW...) 
 `zh-Hans` for Simplified Chinese (简体中文/China-Mainland)

Have a nice time~

**Comment by Azimiao** [comment]
EG:

zh-Hant:

```json
"npServiceName": "trophy",
"npCommunicationId": "NPWR24143_00",
"trophySetVersion": "01.02",
"trophyTitleName": "英雄傳說 黎之軌跡",
"trophyTitleDetail": "《英雄傳說 黎之軌跡》的獎盃組",
```

zh-Hans:

```json
"npServiceName": "trophy2",
"npCommunicationId": "NPWR20188_00",
"trophySetVersion": "01.40",
"trophyTitleName": "宇宙机器人无线控制器使用指南",
```
en-US:

```json
"npServiceName": "trophy2",
"npCommunicationId": "NPWR20188_00",
"trophySetVersion": "01.40",
"trophyTitleName": "ASTRO’s PLAYROOM",
```

**Comment by jacklee0122** [comment]
Thanks very much. I didn't know using "zh-Hant"
