### ISSUE TITLE
psn-api can't be found. 

### ISSUE THREAD

**Issue by SMcGregor199** [achievements-app/psn-api#96]
I want to use this api to display all my games in my browser's console. But for some reason, I'm getting a 404 error because the file "psn-api" can't be found. 

**things i've done**
- I've followed the installation instructions in the documentation ( `npm install psn-api`), 
- I've tried removing the "./" prefix  

I'm attaching an image of my code below as well as the error I'm receiving. I'd appreciate it if someone could pinpoint what I'm doing wrong. I'm pretty new to APis in general. It might be something very simple that I'm overlooking. It might also be helpful to know that I'm not using a javascript-framework. I'm trying to fetch the data in a single .js file, and I'm using the file on an index page with `<script type="module" src="scripts/psn-api.js"></script>`
<img width="798" alt="Screen_Shot_2022-10-10_at_1_14_45_PM-2" src="https://user-images.githubusercontent.com/78387650/194926371-4f17a95f-7b4d-49b1-8096-85dd8ab4a878.png">

<img width="1008" alt="Screen Shot 2022-10-10 at 1 54 08 PM" src="https://user-images.githubusercontent.com/78387650/194926399-95bba3e3-1427-4132-9578-6b0ef3556614.png">

**Comment by wescopeland** [comment]
@SMcGregor199 As this is more closely related to project configuration, I will be closing this issue for now! Please LMK if there are issues with Skypack CDN, and if so maybe we can take things to Stackblitz and come to a resolution.
