### ISSUE TITLE
FetchError: Invalid json response body

### ISSUE THREAD

**Issue by gamerxsocietydev** [achievements-app/psn-api#97]
I have this error being returned after following the get started process. I have updated the npsso code multiple times and am still getting the same error no matter what changes i make. Please help

unhandledRejection: FetchError: invalid json response body at https://m.np.playstation.net/api/search/v1/universalSearch

**Comment by FunkeyFlo** [comment]
It's looking like the v1 api has been killed / changed by sony. All routes seem to be returning 403 errors.

**Comment by wescopeland** [comment]
Major bummer. Should all v1 routes be deprecated / removed?

**Comment by FunkeyFlo** [comment]
Not quite sure yet. Maybe best to wait until tomorrow to be absolutely sure. I've also not tested _all_ routes so more might be affected. Authentication (npsso) process still seems to work though.

**Comment by wescopeland** [comment]
Also @FunkeyFlo -- cool project using psn-api!

**Comment by FunkeyFlo** [comment]
`userProfile/v1/internal/users` is also affected, I was using it to track activities in [my home automation app](https://github.com/FunkeyFlo/ps5-mqtt/blob/main/ps5-mqtt/server/src/psn-account.ts#L111).

**Comment by wescopeland** [comment]
Understood, I believe that would impact:

* `getProfileFromAccountId()`
* `getUserFriendsAccountIds()`

This would probably have been killed off due to the `internal` designation in the path, but unfortunate nonetheless. I will test these and `makeUniversalSearch()` in 24 hours and see if they're still non-functional, and if so we'll have to remove them from the library.

Definitely open to ideas how to replace the implementation of these functions.

**Comment by wescopeland** [comment]
FYI: 
https://github.com/Tustin/psn-php/issues/217
https://github.com/Tustin/psn-php/commit/16032a352b78057bbda03bf956167003570d4cc2

**Comment by wescopeland** [comment]
The solution in the linked commit fixes `makeUniversalSearch()`, `getProfileFromAccountId()`, and `getUserFriendsAccountIds()`. I am about to push a release with this hotfix.

**Comment by sammyke007** [comment]
So .net changed to .com?!

**Comment by wescopeland** [comment]
For "m.np.playstation", yes 🫡

**Comment by wescopeland** [comment]
Thank you for reporting this issue. 2.8.0 has been released with a hotfix.

**Comment by gamerxsocietydev** [comment]
@wescopeland The hot fix from earlier fixed each file except for the "TROPHY_BASE_URL.d.ts" 
file, which is still causing issues when retrieving user trophy information. 

Error Message Reads ->
FetchError: invalid json response body at https://m.np.playstation.net/api/trophy/v1/users/web3_architect/trophySummary reason: Unexpected token < in JSON at position 0
....

I would also like to request help from someone proficient with this repo to get me set back up properly. That would be amazing. Been struggling these past couples of days with making the correct API calls

**Comment by gamerxsocietydev** [comment]
The update to psn-api 2.81 worked!! Thank you very much @wescopeland you are amazing!

**Comment by wescopeland** [comment]
I think the dust has settled and it's safe to close this issue at this point.

**If you are experiencing this issue, upgrading to 2.8.1 should fix it.**
